"""add_user_email_configs

Revision ID: 22e7336faf6b
Revises: 0005_crm_interactions
Create Date: 2026-08-16 17:11:16.697592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22e7336faf6b'
down_revision: Union[str, None] = '0005_crm_interactions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_configs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), server_default='smtp.gmail.com', nullable=False),
    sa.Column('smtp_port', sa.Integer(), server_default='587', nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=True),
    sa.Column('smtp_from_email', sa.String(length=255), nullable=True),
    sa.Column('smtp_from_name', sa.String(length=150), server_default='SalesGenie', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_email_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_email_configs'))
    )
    op.create_index(op.f('ix_user_email_configs_user_id'), 'user_email_configs', ['user_id'], unique=True)
    op.alter_column('sales_interactions', 'interaction_type',
               existing_type=postgresql.ENUM('call', 'email', 'meeting', 'demo', 'other', 'note', 'follow_up', 'stage_change', name='interactiontype'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_si_account_id', table_name='sales_interactions')
    op.drop_index('ix_si_contact_id', table_name='sales_interactions')
    op.drop_index('ix_si_opportunity_id', table_name='sales_interactions')
    op.create_index(op.f('ix_sales_interactions_account_id'), 'sales_interactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_sales_interactions_contact_id'), 'sales_interactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_sales_interactions_opportunity_id'), 'sales_interactions', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_interactions_opportunity_id'), table_name='sales_interactions')
    op.drop_index(op.f('ix_sales_interactions_contact_id'), table_name='sales_interactions')
    op.drop_index(op.f('ix_sales_interactions_account_id'), table_name='sales_interactions')
    op.create_index('ix_si_opportunity_id', 'sales_interactions', ['opportunity_id'], unique=False)
    op.create_index('ix_si_contact_id', 'sales_interactions', ['contact_id'], unique=False)
    op.create_index('ix_si_account_id', 'sales_interactions', ['account_id'], unique=False)
    op.alter_column('sales_interactions', 'interaction_type',
               existing_type=postgresql.ENUM('call', 'email', 'meeting', 'demo', 'other', 'note', 'follow_up', 'stage_change', name='interactiontype'),
               server_default=sa.text("'other'::interactiontype"),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_email_configs_user_id'), table_name='user_email_configs')
    op.drop_table('user_email_configs')
    # ### end Alembic commands ###
